atlasaction/gitlab: show download process and URL (#458)

diff --git a/atlasaction/templates/gitlab-yml.tmpl b/atlasaction/templates/gitlab-yml.tmpl
--- a/atlasaction/templates/gitlab-yml.tmpl
+++ b/atlasaction/templates/gitlab-yml.tmpl
@@ -55,8 +55,13 @@ $[[ inputs.job_name ]]:
 {{- end }}
       BINARY_NAME="atlas-action-${CI_RUNNER_EXECUTABLE_ARCH//\//-}-v1"
       DOWNLOAD_URL="https://release.ariga.io/atlas-action/${BINARY_NAME}"
-      curl -fL -o atlas-action "$DOWNLOAD_URL" || { echo "Failed to download atlas-action from $DOWNLOAD_URL"; exit 1; }
-      chmod +x ./atlas-action
+      echo "Downloading ${DOWNLOAD_URL}"
+      if curl -L -o atlas-action --fail "-#" "$DOWNLOAD_URL"; then
+        chmod +x ./atlas-action
+      else
+        echo "Failed to download atlas-action from $DOWNLOAD_URL" >&2
+        exit 1;
+      fi
 {{- if eq .ID "migrate/diff" }}
       # Set up git
       git fetch $[[ inputs.remote ]] $CI_COMMIT_REF_NAME
