ci/schema-lint: fail only on unexpected rule violations

diff --git a/.github/workflows/ci-go.yaml b/.github/workflows/ci-go.yaml
--- a/.github/workflows/ci-go.yaml
+++ b/.github/workflows/ci-go.yaml
@@ -389,6 +389,18 @@ jobs:
           vars: '{"rulefile":"schema.rule.hcl"}'
         env:
           GITHUB_TOKEN: ${{ github.token }}
+      - name: Mark failure as expected
+        if: |
+          steps.schema_lint_test.outcome == 'failure' &&
+          matrix.test.url != 'file://ok.lt.hcl'
+        run: echo "::notice title=Expected Failure::${{ matrix.test.url }} failed as expected"
+      - name: Fail on unexpected failure
+        if: |
+          steps.schema_lint_test.outcome == 'failure' &&
+          matrix.test.url == 'file://ok.lt.hcl'
+        run: |
+          echo "::error title=Unexpected Failure::${{ matrix.test.url }} must pass"
+          exit 1
   schema-apply:
     runs-on: ubuntu-latest
     env:
